version: "3.8"

services:
  eugenex:
    image: enginenex:alphain
    container_name: todo_app
    restart: unless-stopped
    ports:
      - "80:80"  
    volumes:
      - ./data:/data 
    networks:
      - todo_app_network

  app:
    build:
      context: ./
      dockerfile: Dockerfile  
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - todo_app_network

  db:
    image: mysql:5.6
    container_name: todo_app_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - todo_app_db_volume:/var/lib/mysql
    networks:
      - todo_app_network

networks:
  todo_app_network:
    driver: bridge

volumes:
  todo_app_db_volume:
